### ISSUE TITLE
[BUG] Race Condition In AlsaSequencer.cpp

### ISSUE THREAD

**Issue by Slushie7** [rerdavies/pipedal#550]
**Describe the bug**
Lines 94 and 98 in PiPedalCommon/src/AlsaSequencer.cpp use unnamed temporary lock_guards in the form:

std::lock_guard { connectionsMutex};

Because they are unnamed, and C++ is cursed, the mutex is locked and then immediately unlocked at the semicolon. This creates a possible race condition. Also, because [[nodiscard]] was added to lock_guard's constructor in the newer libstdc++, pipedal v2.0.110 will not compile on GCC 14.2 without those two lock_guards being named so they aren't immediately discarded (e.g. "std::lock_guard lock { connectionsMutex};"

**Build Log**
pitar@pitar:~/pipedal $ ./mk.sh
[  0%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Connection.cpp.o
[  0%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Error.cpp.o
[  0%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Message.cpp.o
[  1%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Object.cpp.o
[  1%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Proxy.cpp.o
[  1%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Types.cpp.o
[  1%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/Flags.cpp.o
[  2%] Building C object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/VTableUtils.c.o
[  2%] Building CXX object modules/sdbus-cpp/CMakeFiles/sdbus-c++-objlib.dir/src/SdBus.cpp.o
[  2%] Built target sdbus-c++-objlib
[  3%] Building CXX object PiPedalCommon/src/CMakeFiles/PiPedalCommon.dir/AlsaSequencer.cpp.o
/home/pitar/pipedal/PiPedalCommon/src/AlsaSequencer.cpp: In member function ‘int32_t pipedal::impl::AlsaSequencerImpl::midiChannel()’:
/home/pitar/pipedal/PiPedalCommon/src/AlsaSequencer.cpp:94:51: error: ignoring return value of ‘std::lock_guard<_Mutex>::lock_guard(mutex_type&) [with _Mutex = std::mutex; mutex_type = std::mutex]’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
   94 |                 std::lock_guard { connectionsMutex};
      |                                                   ^
In file included from /usr/include/c++/14/bits/atomic_wait.h:51,
                 from /usr/include/c++/14/bits/atomic_base.h:42,
                 from /usr/include/c++/14/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/14/memory:81,
                 from /home/pitar/pipedal/PiPedalCommon/src/include/AlsaSequencer.hpp:28,
                 from /home/pitar/pipedal/PiPedalCommon/src/AlsaSequencer.cpp:24:
/usr/include/c++/14/bits/std_mutex.h:249:16: note: declared here
  249 |       explicit lock_guard(mutex_type& __m) : _M_device(__m)
      |                ^~~~~~~~~~
/home/pitar/pipedal/PiPedalCommon/src/AlsaSequencer.cpp: In member function ‘void pipedal::impl::AlsaSequencerImpl::midiChannel(uint32_t)’:
/home/pitar/pipedal/PiPedalCommon/src/AlsaSequencer.cpp:98:51: error: ignoring return value of ‘std::lock_guard<_Mutex>::lock_guard(mutex_type&) [with _Mutex = std::mutex; mutex_type = std::mutex]’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
   98 |                 std::lock_guard { connectionsMutex};
      |                                                   ^
/usr/include/c++/14/bits/std_mutex.h:249:16: note: declared here
  249 |       explicit lock_guard(mutex_type& __m) : _M_device(__m)
      |                ^~~~~~~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [PiPedalCommon/src/CMakeFiles/PiPedalCommon.dir/build.make:79: PiPedalCommon/src/CMakeFiles/PiPedalCommon.dir/AlsaSequencer.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1581: PiPedalCommon/src/CMakeFiles/PiPedalCommon.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2

** Environment (please complete the following information):**
 - OS: Raspberry Pi OS Lite (Trixie)
 - Linux pitar 6.18.34+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.18.34-1+rpt1 (2026-06-09) aarch64 GNU/Linux
- Raspberry Pi 5 4GB
- PiPedal v2.0.110
- GCC Version 14.2.0

**Comment by rerdavies** [comment]
Truly cursed, especially on that one. 

Fixed in dev. Will propagate to main on the next release. 

It's actually more of a read/write barrier problem on AARCH64 only, and mostly harmless (I think).

If you need a build, you can change lines 94 and 98 to 

    std::lock_guard lockGuard { connectionsMutex};

**Comment by rerdavies** [comment]
You're not having install issues on trixie, are you?

**Comment by Slushie7** [comment]
I appreciate the quick response. I can install the precompiled .deb file on my Pi running trixie with no issues. The issue only came to my attention when I was trying to build from the source. I have a slightly tweaked build of pipedal that I run on my battery-powered Pi guitar - I add some basic differential audio to AlsaDriver.cpp to cut out some noise, and I set the Pi's governor in PiPedalModel.cpp to "ondemand" to save a bit of battery life. Updating lines 94 and 98 fixed the build issue for me. Thank you.
